version: '3.7'

services: 
  mysqldb:
    image: mysql
    container_name: database_beeleads
    restart: always
    ports: 
      - 3366:3306
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
  app:
    build: .
    container_name: beeleads
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    links: 
      - mysqldb
    depends_on: 
      - mysqldb

volumes: 
  db-config:
  db-data:  